### ISSUE TITLE
Error of Game load

### ISSUE THREAD

**Issue by antisocialian** [Shirkit/PersonalRoboportFix#2]
Getting an Error on loading a game while this mod is installed after the 0.12.11 update(no change with any of the subsequent updates either). I can't get into any save games while this mod is enabled

The game pops up a message stating " _ _PersonalRoboportFix_ _/control.lua:22: attempt to index global 'game' )a nil value)"

I have uploaded a screenshot of the error as well if that will help http://i.imgur.com/iuiHqq9.png

**Comment by pa-philos** [comment]
Hello antisocialian, thanks for the report. Thanks to you I got an email warning me of the issue =] It's now fixed and should be working, the fix took me 10 seconds. Took way longer to update the thread and everything else! I much appreciate.
