### ISSUE TITLE
not working in 0.12.29

### ISSUE THREAD

**Issue by Goten87** [Shirkit/PersonalRoboportFix#3]
the mod will not work in 0.12.29
its saying disable and it have no power but it still uses my robos

**Comment by Goten87** [comment]
oke nvm 1 of my ports dint want to update
also can u make it if we press a butten it will turn on again?

**Comment by pa-philos** [comment]
The bad thing is that the button can't be a hotkey for now, it has to be a button on the GUI, so it would be ugly. Unless you REALLY want it, I do not think it's a good idea. Now if you really need it, then I can try to take a look, but need your answer first.

**Comment by Goten87** [comment]
No it's not realy needed it's just a nice thing to have to put them on/off when u want it

**Comment by pa-philos** [comment]
I agree that is a nice thing to have, but I've yet to find a use case for
it. I'll wait till 0.13 when they said we'd be able to set hotkeys.
