### ISSUE TITLE
Please update for 0.13

### ISSUE THREAD

**Issue by georgehank** [Shirkit/PersonalRoboportFix#5]
It needs (at least) a factorio_version line in info.json, but I'm sure that's not enough.

**Comment by pa-philos** [comment]
It actually needs another fix, I'll probably take a couple of hours this week to push an update.

**Comment by poma** [comment]
Please update for 0.14

**Comment by pa-philos** [comment]
Sorry but https://mods.factorio.com/mods/mknejp/personal-roboport-switch
